title: PML Blog
name: pml-blog
email: pmleva2@gmail.com
author: Pierre-Marc Levasseur
description: >
  Blog personnel pour partager mes expériences et mes opinions en tant que développeur logiciel.
url: "http://pml-blog.com"
github_username:  PMarcL

# comments
disqus:
  shortname: pml-blog

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
