title: PML Blog
email: pmleva2@gmail.com
author: Pierre-Marc Levasseur
description: >
  Blog personnel pour partager mes expériences et mes opinions en tant que développeur logiciel.
baseurl: "/pml-blog"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  PMarcL

# comments
disqus:
  shortname: pml-blog

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
